name: 'Terraform container actions'
description: 'Terraform action for demos'
author: 'mattallen889'
inputs:
  ARM_CLIENT_ID: 
    description: 'AZ client id'
    required: true
  ARM_CLIENT_SECRET:
    description: 'Azure client secret'
    required: true
  ARM_SUBSCRIPTION_ID:
    description: 'Azure subscription id'
    required: true
  ARM_TENANT_ID: 
    description: 'Azure tenant id'
    required: true
  STATE_KEY: 
    description: 'Unique value to identify your state slice'
    required: true
  TF_STAGE:
    description: 'The stage to deploy'
    required: true
  DJANGO_SECRET_KEY_PROD: 
    description: 'The secret key for django to start'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'

  
    
